# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  """The Calculator Service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTwoNumbers = channel.unary_unary(
        '/Calculator/AddTwoNumbers',
        request_serializer=calculator__pb2.AddRequest.SerializeToString,
        response_deserializer=calculator__pb2.SumReply.FromString,
        )


class CalculatorServicer(object):
  """The Calculator Service definition
  """

  def AddTwoNumbers(self, request, context):
    """Sends two numbers as input
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTwoNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.AddTwoNumbers,
          request_deserializer=calculator__pb2.AddRequest.FromString,
          response_serializer=calculator__pb2.SumReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
